url: https://mr0null.github.io
baseurl:

# Site settings
title: Persepolis Download Manager
logo: logo.png
email: persepolis@beeit.ir
description: "Persepolis Download Manager, is a graphical user interface (GUI) for aria2! Now it supports MacOs and all gnu/linux distributions."


# Team names, titles and social links
people:
- name: Alireza AmirSamimi
  pic: 1
  position: Lead Programmer
  social:
    - title: github
      url: http://github.com/alireza-amirsamimi

- name: MohammadAmin Vahedinia
  pic: 2
  position: MacOS Support
  social:
    - title: github
      url: http://github.com/Mr0Null

- name: Mostafa Asadi
  pic: 3
  position: Ubuntu Support
  social:
    - title: github
      url: http://github.com/mostafaasadi

- name: Sadegh Alirezaie
  pic: 4
  position: Site Support
  social:
    - title: github
      url: http://github.com/AlirezaieS

- name: MohammadReza AbdollahZade
  pic: 5
  position: Arch Repo
  social:
    - title: github
      url: http://github.com/morealaz
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/persepolisdm
  - title: github
    url: https://github.com/persepolisdm/persepolis
  - title: paper-plane
    url: https://telegram.me/persepolisdm

# Build settings
markdown: kramdown
permalink: pretty
