url: https://mr0null.github.io
baseurl:

# Site settings
title: Persepolis Download Manager
logo: logo.png
email: persepolis@beeit.ir
description: "Persepolis Download Manager, is a graphical user interface (GUI) for aria2! Now it supports MacOs and all gnu/linux distributions."


# Team names, titles and social links
people:
- name: Alireza AmirSamimi
  name-fa: علیرضا امیرصمیمی
  pic: https://avatars2.githubusercontent.com/u/7452500?v=3&s=400
  position-fa: برنامه‌نویس ارشد
  position: Lead Programmer
  social:
    - title: github
      url: http://github.com/alireza-amirsamimi

- name-fa: محمدامین واحدی‌نیا
  name: MohammadAmin Vahedinia
  pic: https://avatars1.githubusercontent.com/u/16556650?v=3&s=460
  position: MacOS Support
  position-fa: پشتیبانی مک
  social:
    - title: github
      url: http://github.com/Mr0Null

- name-fa: مصطفی اسدی
  name: Mostafa Asadi
  pic: https://avatars0.githubusercontent.com/u/12208050?v=3&s=466
  position-fa: پشتیبانی اوبونتو
  position: Ubuntu Support
  social:
    - title: github
      url: http://github.com/mostafaasadi

- name-fa: صادق علیرضایی
  name: Sadegh Alirezaie
  pic: https://avatars0.githubusercontent.com/u/16784257?v=3&s=400
  position: Site Support
  position-fa: پشتیبانی سایت
  social:
    - title: github
      url: http://github.com/AlirezaieS

- name-fa: محمدرضا عبدالله‌زاده
  name: MohammadReza AbdollahZade
  pic: https://avatars3.githubusercontent.com/u/2796369?v=3&s=400
  position: Arch Repo
  position-fa: پشتیبانی آرچ
  social:
    - title: github
      url: http://github.com/morealaz
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/persepolisdm
  - title: github
    url: https://github.com/persepolisdm/persepolis
  - title: paper-plane
    url: https://telegram.me/persepolisdm

# Build settings
markdown: kramdown
permalink: pretty
